### ISSUE TITLE
show nnUNet attention maps 

### ISSUE THREAD

**Issue by JunMa11** [MECLabTUDA/M3d-Cam#1]
Dear @MECLabTUDA ,

Thanks for the awesome work.

Would it be possible for you to give an example to show the attention maps of [nnUNet](https://github.com/MIC-DKFZ/nnUNet), which is one of the most popular segmentation networks?

Best regards,
Jun

**Comment by Karol-G** [comment]
Hi Jun,

there is actually a nnUNet jupyter demo. You can find it at the end of the readme. I have added a google colab link so you can open and test it in colab.

Best,
Karol

**Comment by JunMa11** [comment]
Got it. 

Thank you very much. Really nice work.

Best,
Jun
