### ISSUE TITLE
Issue including medcam as a dependency in conda package

### ISSUE THREAD

**Issue by sarthakpati** [MECLabTUDA/M3d-Cam#11]
Hey,

I am trying to install `medcam` as a [conda dependency](https://anaconda.org/conda-forge/medcam) for GaNDLF but I am getting the [following error](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=336728&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=660):

```
pkg_resources.DistributionNotFound: The 'opencv-python' distribution was not found and is required by medcam
```

Which is completely legit because conda doesn't publish `opencv-python` (they publish [opencv directly](https://anaconda.org/conda-forge/opencv), which works with the `cv2` namespace in python).

I propose to put `opencv-python` as an optional installation target that gets triggered when installing through pip and removing it as a dependency in the `install_requires` of `setup.py`. I can put in a PR that highlights a prototype for this.

Cheers,
Sarthak

**Comment by Karol-G** [comment]
Thanks for the fix. I merged it 👍
