### ISSUE TITLE
how can Patch-based 3d segmentation get full heatmap 

### ISSUE THREAD

**Issue by Da1daidaidai** [MECLabTUDA/M3d-Cam#29]
Thanks for your geart work. 

Some 3d image is too large that it uses patch to crop the whole image (200*200*300) into patches(96*96*96) . when using medcam, how can we get one full heat map  of such pathch-based inference ?

**Comment by Karol-G** [comment]
Hey,

you will need to aggregate the heatmap patches back to the original image size. You can use the GridSampler and Grid Aggregator from TorchIO for that ([https://torchio.readthedocs.io/patches/patch_inference.html](https://torchio.readthedocs.io/patches/patch_inference.html)).

Best,
Karol

**Comment by Da1daidaidai** [comment]
Thank you for your quick reply :)

I tried the sliding_window_inference in MONAI, it give a full return, while the whole heatmap is black
I have tried different model like unet dyunet , the result is the same.
Is there any solution?

Thanks again :）
