### ISSUE TITLE
error on 'from medcam import medcam'

### ISSUE THREAD

**Issue by 9B8DY6** [MECLabTUDA/M3d-Cam#7]
![image](https://user-images.githubusercontent.com/67573223/111482912-adb35080-8777-11eb-9b66-277fdcc47766.png)

I got this error on 'from medcam import medcam'

What should I do to solve it?

**Comment by Karol-G** [comment]
Hi,

I failed to reproduce your problem, everything works well for me.
Also it seems that the error originates from Numpy. Which version are you using? Maybe try to update it.
Or in case you are using the newest version, try 1.19.4 which is my current.

Best
Karol

**Comment by 9B8DY6** [comment]
![image](https://user-images.githubusercontent.com/67573223/111506822-61730b00-878d-11eb-96cf-f40226c1e152.png)
it does not work even if I upgrade version of numpy. Could you tell me the version of other things?

**Comment by Karol-G** [comment]
scikit-image 0.16.2
scikit-learn 0.24.0
python 3.8.2
pytorch 1.5.0

Try to update your scikit-image maybe, according to this link the error could come from scikit-image:
https://github.com/scikit-image/scikit-image/issues/3649
